### ISSUE TITLE
关于代码说明问题

### ISSUE THREAD

**Issue by yangchangdong** [laraver/eleme-sdk#16]
在你的说明中

> PS: 其他请参考 https://github.com/hanson/eleme-sdk/blob/master/src/Eleme.php 中的备注

在代码中并不有找到是忘记传了吗。

**Comment by Hanson** [comment]
什么意思？一头雾水？

**Comment by Hanson** [comment]
明白你的意思了，这个是容器，实现方式可以看看 pimple 和 服务提供者的代码
